### ISSUE TITLE
TSYTextStorage in Swift?

### ISSUE THREAD

**Issue by mattmassicotte** [ChimeHQ/TextStory#2]
Originally, this library was all Swift. However, I ran into some terrible performance issues, that I eventually tracked down to interactions between NSString and Swift String conversions. This surprised me quite a bit, but it seems like the Cocoa text system heavily depends on string reference semantics for performance in this area.

I have to confess that I did some searches, found others with similar issues, and then just wrote the class in ObjC and moved on. It's a very straight-forward implementation. But, it would be pretty interesting to see if/how this could be done in Swift. It's been a while, so perhaps things have changed?

**Comment by catlan** [comment]
### Efficient Interactions with Frameworks

> The NSText storage is a subclass of NSMutableAttributedString. Now, since NSText storage is intended for working with text editing, it's reasonable to expect the contents of that text storage to be mutated, frequently. And the contents of the text storage could also be a very long string. It could be megabytes or even gigabytes in size. And so, for efficiency, the framework only keeps the mutable string around. So, when you ask for that string property on the text storage, what you'll get is going to be backed by an NSString that refers to the mutable string.
>
> And so now, once again, we'll take a look at what happens when we ask for that string property from Swift. Just as before, it'll be wrapped in the value type when it crosses the bridge, because it's an NSString. And the framework is going to make a copy. But unlike in the UILabel case, here the underlying NSString is actually mutable. So, this copy could be expensive.
>
> And as we said previously, text storage is much more likely to contain long length strings.
>
> It could be megabytes or even gigabytes in size, so potentially this copy could be very expensive. But now, let's take a look at what happens when we ask for the mutable string property. NSMutableString is a reference type that is not bridged.
>
> And because it's not bridged, there's no copy. So, we avoid the cost of the copy, here. This situation results from a mismatch between Swift's value semantics and the design of NSText storage, which needs to use reference semantics for performant management of large amounts of text. So, we're working on solving this problem, here at Apple. But we don't quite have the solution, yet.
>
> So, you should be aware that this is something that can happen.
>
> And if you're working with very large amounts of text and the text storage, use MutableString to access it, even if you don't plan on mutating it. But before you go bananas changing all of your string accesses to MutableString, let's consider that graph, again.
>
> Now, due to the nature of the text storage API, you're probably going to be up here on the top half, in terms of frequency. So then, the real question becomes, how much text do you expect that storage to contain? A kilobyte? Might be in here, it's not too bad. If you use the string property, that's probably fine. One megabyte? You're starting to move into first quadrant territory, here. And you may want to consider using MutableString.
>
> One gigabyte? I really hope you're using MutableString.
>
> And as I said, we're working on fixing this on our end, here. So, keep an eye out for it in future releases. And so, now that we have a better understanding of string bridging, let's move on.

[https://developer.apple.com/videos/play/wwdc2017/244/](https://developer.apple.com/videos/play/wwdc2017/244/)

**Comment by mattmassicotte** [comment]
Thank you. So that pretty much matches what I saw. Very good to know, but I guess this must stay as-is.
