### ISSUE TITLE
After dragging the attachment, the textview does not release

### ISSUE THREAD

**Issue by XavierLost** [ChimeHQ/TextStory#3]

**Comment by mattmassicotte** [comment]
Hello, and thank you for this report!

Sounds like you are seeing a memory leak. Would you please provide some more details on how you are using TextStory, what you are doing to trigger it, and and more info you might have on how TextStory is involved.

**Comment by mattmassicotte** [comment]
Thanks again for reporting this, but without more information I'm not sure there's much I can help with. I'd like to keep investigating, so please open another issue if you want to look again.
